### PR TITLE
Fix typos in `DEVELOPER/`

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Comment by luzpaz** [comment]
Rebased

**Comment by luzpaz** [comment]
Rebased. Looks like the CI is failing due to:  
```
CMake Error at /usr/local/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TCLTK (missing: TK_INCLUDE_PATH)
-- Configuring incomplete, errors occurred!
```

**Comment by luzpaz** [comment]
@mhscott was this just closed or merged separately ?

**Comment by mhscott** [comment]
It was closed. We appreciate the effort to spell check. The changes are numerous, but inconsequential. We will continue to fix spelling errors where appropriate when updating the source code.

**Comment by luzpaz** [comment]
fair enough

**Comment by luzpaz** [comment]
JFYI, it's possible to implement a `.git-blame-ignore-revs` (https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/) if you're worried about git log pollution.

**Pull request closed without merging**
