### PR TITLE
Bringing in several enhancements

### PR DESCRIPTION
**Pull request by jaabell**
- I did some bugfixes for the MPCORecorder to make it useful in OpenSeesSP. 
- More enhancements for H5DRM load pattern
- Several performance boosts for OpenSeesSP

### CODE REVIEW

**Comment by jf-huang** [comment]
Hi Dr. Abell,

Thank you for the enhancements! I tried to use your lastest MPCORecorder.cpp code after commenting out "#define MPCO_HDF5_LOADED_AT_RUNTIME” but it would give me some error as show below if I run it in parallel using OpenSeesSP:

```
root@a8f0c1f041f0:/home/ops# mpirun -np 3 OpenSeesPARALLEL Pushover.tcl 
Primary Process Running OpenSees Interpreter 0


         OpenSees -- Open System For Earthquake Engineering Simulation
                 Pacific Earthquake Engineering Research Center
                        Version 3.2.2 64-Bit

      (c) Copyright 1999-2016 The Regents of the University of California
                              All Rights Reserved
  (Copyright and Disclaimer @ http://www.berkeley.edu/OpenSees/copyright.html)


Secondary Process Running 1
Secondary Process Running 2
MPCO recorder - Written by ASDEA Software Technology: M.Petracca, G.Camata
ASDEA Software Technology: https://asdeasoft.net
STKO (Scientific ToolKit for OpenSees): https://asdeasoft.net/stko/
If you use this tool, please cite us:
Petracca, M., Candeloro, F., & Camata, G. (2017). "STKO user manual". ASDEA Software Technology, Pescara Italy.        
MPCORecorder sendSelf from: 0, send self count = 1
MPCORecorder sendSelf from: 0, send self count = 2
MPCORecorder recvSelf from: 1, send self count = -1
filename = mpcoRecorder.hdf5
freq: dt = 0
nodal results [1]
   0
elemental results [0]
node set:
[]
elem set:
[]
MPCORecorder recvSelf from: 2, send self count = -1
filename = mpcoRecorder.hdf5
freq: dt = 0
nodal results [1]
   0
elemental results [0]
node set:
[]
elem set:
[]
MPI_Channel::recvID() - incorrect number of entries for ID received: 1 exptected: 4
ActorSubdomain::run - error receiving msgData
MPI_Channel::recvID() - incorrect number of entries for ID received: 1 exptected: 4
ActorSubdomain::run - error receiving msgData
Fatal error in MPI_Recv: Message truncated, error stack:
MPI_Recv(184)...........................: MPI_Recv(buf=0x55d555b830f0, count=1, MPI_INT, src=0, tag=0, MPI_COMM_WORLD, 
status=0x7ffccf8e1370) failed
MPIDI_CH3_PktHandler_EagerShortSend(349): Message from rank 0 and tag 0 truncated; 16 bytes received but buffer size is 4
Fatal error in MPI_Recv: Message truncated, error stack:
MPI_Recv(184)...........................: MPI_Recv(buf=0x5570a9b2c0f0, count=1, MPI_INT, src=0, tag=0, MPI_COMM_WORLD, 
status=0x7ffc852a4b90) failed
MPIDI_CH3_PktHandler_EagerShortSend(349): Message from rank 0 and tag 0 truncated; 16 bytes received but buffer size is 4

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

This problem seemed to exist before this enhancement. However, it did not return error when I ran with only 1 core ("mpirun -np 1 OpenSeesPARALLEL Pushover.tcl" or "OpenSeesPARALLEL Pushover.tcl") and the *.mpco result file looked fine. Do you know where could possibly go wrong? Would glad to provide more info if needed. Thanks!

Regards,
Junfei

**Comment by jaabell** [comment]
Hello Junfei. ¿Were you able to run these cases?
I would suspect that error has to do with the types of output you're requesting. What are you requesting?

**Comment by jf-huang** [comment]
Hello Dr. Abell, 

Thanks for looking into this. Yes, I was able to run the model and get the mpco hdf5 result file with 1 core. I was only requesting the node displacements (recorder mpco mpcoRecorder.hdf5 -N displacement) and the result file looked right. The output info when running with 1 core is shown below:
```
root@5888f6ab4cdc:/home/ops# OpenSeesPARALLEL main.tcl
Primary Process Running OpenSees Interpreter 0


         OpenSees -- Open System For Earthquake Engineering Simulation
                 Pacific Earthquake Engineering Research Center
                        Version 3.2.2 64-Bit

      (c) Copyright 1999-2016 The Regents of the University of California
                              All Rights Reserved
  (Copyright and Disclaimer @ http://www.berkeley.edu/OpenSees/copyright.html)


MPCO recorder - Written by ASDEA Software Technology: M.Petracca, G.Camata
ASDEA Software Technology: https://asdeasoft.net 
STKO (Scientific ToolKit for OpenSees): https://asdeasoft.net/stko/ 
If you use this tool, please cite us:
Petracca, M., Candeloro, F., & Camata, G. (2017). "STKO user manual". ASDEA Software Technology, Pescara Italy.
Step 1 / 10
ID::resize() - size specified 0 <= 0
Step 2 / 10
Step 3 / 10
Step 4 / 10
Step 5 / 10
Step 6 / 10
Step 7 / 10
Step 8 / 10
Step 9 / 10
Step 10 / 10
Process Terminating 0
```
I compiled OpenSeesSP on ubuntu with mpich2 and hdf5-1.10.4. Could the problem come from the mpi or hdf5 version that I am using? Attached is a simple 1-story 1-bay model that I have tested if you'd like to try it out. It also contains the recorded hdf5 result file.  Thanks!

Regards,
Junfei

[1story1bay.zip](https://github.com/OpenSees/OpenSees/files/5600489/1story1bay.zip)

**Comment by MassimoPetracca** [comment]
@jf-huang and @jaabell , I noticed some times (not always) the same behavior with OpenSeesSP with multiple processors. I think it's due to (don't know why) the fact that some send-recv pairs are not syncronized correctly... I mean they are sent and received in different orders.
I think this happens with the MPCORecorder because I sent mutliple messages there, since a single vector is not enough to store all those heteorogeneous data.
So now I'm working on a possible workaroud:
Instead of sending multiple messages, I send just 1 with a string where I serialize all the data I need, and then I de-serialize it on the other side.
I will make a PR as soon as I test it.

**Comment by jf-huang** [comment]
@MassimoPetracca Great, thank you!

**Comment by jaabell** [comment]
Hello @MassimoPetracca. I did a few fixes to the MPCO recorder for it to work on OpenSeesSP. Its working fine for me with these changes. I can import the results into STKO just fine. There were a few issues with the send/recv in the class.

**Comment by fmckenna** [comment]
Jose,

you need to put an ifdef around the hdf5 stuff as not all windows develoeprs have the lib. the FEMObjecrBrokerAllClasses file .. _H5DRM

**Comment by jaabell** [comment]
Done!

**Comment by jaabell** [comment]
> Jose,
> 
> you need to put an ifdef around the hdf5 stuff as not all windows develoeprs have the lib. the FEMObjecrBrokerAllClasses file .. _H5DRM

I've added the guard.

**Comment by MassimoPetracca** [comment]
@jaabell ,
I'm creating now a PR to change the way the MPCORecorder does the sendSelf/recvSelf (now I serialize everything into a string) and send just one message, instead of multiple data. I've seen that an example shared by @jf-huang did not work with the previous implementation, while it works with the new one.

**Comment by jaabell** [comment]
Hi Massimo. I think your idea is the correct one. I don't remember why I commented that out in my code. I'm sorry I pushed that.

**Comment by MassimoPetracca** [comment]
@jaabell No problem, thanks!
I'll make a PR with that line fixed, and other fixes to the MPCORecorder for OpenSeesSP

**Pull request merged**
