### PR TITLE
Adding factoronce to the Modified Newton and enhancing the embeddemBeaminterface elements implementation

### PR DESCRIPTION
**Pull request by amnp95**
This pull reuest include adding the factorOnce option or modified newton algorithm and enhancing the Implementation of embeddedInterfaceelements by implementing recvself() and sendSelf() for parallel processing

### CODE REVIEW

**Comment by mhscott** [comment]
Please move the #defines, e.g., `#define SL_NUM_NODE 4`, from the cpp files to private enum statements in the h files. You are redefining pre-processor directives, which some compilers do not like.
e.g.
```cpp
private:
   enum {SL_NUM_NODE=4};
```

**Comment by amnp95** [comment]
Hi I just fixed the macros

**Comment by zhuminjie** [comment]
There is an API, OPS_GetDomain, https://github.com/OpenSees/OpenSees/blob/2edbabe6f99f24a53fc370f81315704d07971de3/SRC/api/elementAPI.h#L176

that can be used to get a pointer to the domain. Should work in Tcl and Python

**Comment by mhscott** [comment]
Thanks, @zhuminjie!

@amnp95 You should do something like this in your code:
```cpp
Domain* theDomain = OPS_GetDomain();
```

**Pull request merged**
