### PR TITLE
New Uniaxial Material; GMG_CyclicReinforcedConcrete

### PR DESCRIPTION
**Pull request by RasoolGhorbaniGitHub**
I have added a new uniaxial material model for simulating the cyclic behavior of reinforced concrete members. For more information please refer to either my dissertation or my EESD paper:
-Dissertation: Ghorbani, R. (2022). Computational Framework for Decision-Oriented Reinforced Concrete Column Simulation Capabilities. Ph.D., The University of Texas at San Antonio.
-Paper: Ghorbani, R., A. Suselo, S. Gendy, A. Matamoros and W. Ghannoum (2022). "Uniaxial model for simulating the cyclic behavior of reinforced concrete members." Earthquake Engineering & Structural Dynamics.

Thank you very much for your attention in advance.
Kind regards,
Rasool Ghorbani

### CODE REVIEW

**Comment by mhscott** [comment]
Please also address the following:
1. Add documentation at https://github.com/OpenSees/OpenSeesDocumentation
2. sendSelf/recvSelf will not work. You create vectors of length 48 but you are sending like 300 values (seg fault will occur)
3. Add the material to the Python interpreter. Easy, look at other materials in SRC/interpreter/OpenSeesUniaxialMaterialCommands.cpp

**Comment by silviamazzoni** [comment]
@RasoolGhorbaniGitHub .... any update?

**Comment by RasoolGhorbaniGitHub** [comment]
I am still working on the documentation part.
________________________________

**Comment by mhscott** [comment]
@RasoolGhorbaniGitHub Do we close this one?

**Comment by RasoolGhorbaniGitHub** [comment]
Yes please. Didn't know how to sync my branch with the latest source code, so I made a new pull request. Both source code and documentation were merged by Dr. Mckenna today.

Thank you

________________________________

**Pull request closed without merging**
