### PR TITLE
Added ndm and ndf utility commands

### PR DESCRIPTION
**Pull request by ambaker1**
Utility commands for getting the input ndm and input ndf, as well as the nodal ndm and ndf. Syntax:
getNDM<$nodeTag>
getNDF<$nodeTag>
If the nodeTag argument is provided, it will return the nodal dimensions/degrees of freedom, or throw an error if the node does not exist.
If the nodeTag argument is not provided, it will return the input ndm/ndf, or the blank string if the model builder is undefined.

### CODE REVIEW

**Comment by ambaker1** [comment]
Alternatively, the commands could be called getNDM and getNDF

**Comment by mhscott** [comment]
Looks like there's a conflict now after merge of getClassType

**Comment by ambaker1** [comment]
It should be fixed now.

**Comment by mhscott** [comment]
Wait like 45 minutes then check again :)

**Comment by ambaker1** [comment]
The merge had some CR/LF issues, apologies for the large # of "modified" lines.

**Pull request merged**
