### PR TITLE
Time-dependent concrete material models

### PR DESCRIPTION
**Pull request by ntosic87**
This version contains four time-dependent concrete material models (TDConcrete, TDConcreteEXP, TDConcreteMC10 and TDConcreteMC10NL) and a new analysis procedure (Creep analysis).
http://dx.doi.org/10.17632/z4gxnhchky.2

### CODE REVIEW

**Comment by mhscott** [comment]
Thank you for sharing your code via this PR!
- The DOI link is invalid
- Why are the source files in DEVELOPER/ and not in SRC/material/uniaxial like the source code for all other uniaxial material models?
- There are conflicts in the VC++ project files.  Shouldn't you resolve them before making the PR?
- SensitivityAlgorithm is not where one would want to add new analysis algorithms.  That should be in the SRC/analysis/analysis directory.  I do not see why you added options in SensitivityAlgorithm.

**Comment by ntosic87** [comment]
Dear prof. Scott,
Thank you for the quick reply. I apologize for the DOI not working, it is a Mendeley dataset with a manual explaining the use and features of the material models (I see now that it is still under review hopefully it will be published soon, I am attaching the manual here).
I was exchanging emails previously with prof. McKenna trying to explain what is the code being developed (it is an update/continuation of work done in 2011 that in the meantime had to be update to become compatible with the new version of OpenSees).
As for your question:
1) I will move the material models into appropriate folders in SRC, I apologize for this, the reason was only ease of my reference in locating the files
2) I am not sure I understand the conflicts of the VC++ project files you mention, could you explain please? I did encounter problems with the original code compiling it in VS2017, some .lib files were missing and references in the material/uniaxial folder.
3) Some coding was done originally in Sensitivity Algorithm but I was sure I removed it. I will double check - could you tell me which lines are problematic?
I apologize for the inconvenience, this was all my first attempt at working in C++, VS, GitHub, etc.
[TDConcrete_Manual.pdf](https://github.com/OpenSees/OpenSees/files/3838125/TDConcrete_Manual.pdf)

**Comment by ahartloper** [comment]
As well, is it necessary to add the libraries in the Win64/lib/ directory?

**Comment by ntosic87** [comment]
Thank you for the question! Unfortunately, for me at least is was, what I did was I first downloaded the entire original source code and tried to compile OpenSees without my code. I was working in VS2017.
I had two things I had to do:
1) in the material and tcl projects I had to "include additional directories" in the C++/General properties - ..\..\..\SRC\material\uniaxial\stiffness; ..\..\..\SRC\material\uniaxial\strength; and ..\..\..\SRC\material\uniaxial\loading; and
2) In the Win64/lib folder I had to add ifconsol.lib; libdecimal.lib; libifcoremt.lib; libifport.lib; libirc.lib; libmmt.lib; and svml_dispmt.lib. The OpenSees project would not compile without them. When I checked previous versions of the OpenSees code these files were there in the first place.

**Comment by ntosic87** [comment]
Dear all,
If possible, can you please provide me with some further clarifications on what I should do to resolve the existing conflicts and enable merging this pull request?
Unfortunately, as I said, I am pretty new to both C++ and VS so any help is greatly appreciated.
Also, it would be a great accomplishment for me and my supervisor if this code would enter OpenSees as we believe it can offer a lot of possibilities for other researchers to model time-dependent behavior of concrete.
Note: the DOI provided in the first message is now active

**Comment by zhuminjie** [comment]
You may want look at the readme below for learning Git, which is a version control system

https://github.com/OpenSees/OpenSees/blob/master/README

**Comment by ntosic87** [comment]
Thank you for the link Dr. Zhu!
I believe I've managed to fork OpenSees to https://github.com/ntosic87/OpenSees
and I've submitted a pull request.
However, as prof. Scott noted there are some conflicts in VC++ project files – this is the part I don't understand since I do not see any problems when I compile OS on my computer using the forked code that is on my GitHub page.
The conflicting files are listed here but I am not sure what I need to do to address the problem.

The thing is that I had to make some changes to the Win64 solution for VS2017 - adding some missing links in material and tcl projects and .lib files to the Win64 solution.
The other comments are related to source code files and placement of the files in the folders, this I more or less understand what to do.

**Comment by zhuminjie** [comment]
The conflicts are due to new commits that made similar changes of yours. Your changes can not automatically merged. That's why you need learn some basics of Git to resolve these conflicts before merging into the main repo. Git is a different thing to C++ or VS. It is a version control system. It compares your changes with exiting changes. So take a look at the Git tutorial (links in the readme), it has commands to fix the conflicts.

**Comment by ntosic87** [comment]
OK, I will go through it in detail, thank you!
I'll probably be back with new questions however:)

**Comment by mhscott** [comment]
It might be best we close this pull request.  What do you think @fmckenna and @zhuminjie ?

**Comment by ntosic87** [comment]
Dear prof. Scott, I assume it means the changes are not accepted - can I submit a new one after this one is closed? I can resolve placing the material models in the appropriate folder, I am just not sure what to do with the sensitivity algorithm you mentioned.
Again, sorry for the inconvenience and thanks for your understanding.

**Comment by mhscott** [comment]
Yes, I should have explained.  There's a lot of extraneous changes you just added the PR and I think you're still overwriting some recent pull requests, e.g., in Newmark.  It's probably better to start over and add the materials according to suggestions from others on this thread.  You can submit another PR later.

**Comment by ntosic87** [comment]
Thank you, I will try to go over things once more in detail, following these guidelines and submit another PR later on.

**Pull request closed without merging**
