### PR TITLE
Adding RockingBC element

### PR DESCRIPTION
**Pull request by vavgen**
Please include the RockingBC element in OpenSees library. The RockingBC element can be used to describe the rocking motion of 2d deformable bodies, either elastic or inelastic, under static or dynamic loading. Apart from the deformability along the length of the member, the element is able to account for deformability near the contact area, where nonlinear stress distributions develop and sections do not remain plane. Furthermore, the element is able to account for constraints along the length of the rocking member imposed by other structural members, as well as sliding and upthrow.

References:
1. Avgenakis E. and Psycharis I.N. (2017) “Modeling of Rocking Elastic Flexible Bodies under Static Loading Considering the Nonlinear Stress Distribution at Their Base.” Journal of Structural Engineering 143(7): 04017051.
2. Avgenakis, E. and Psycharis, I. N. (2019) “Determination of the nonlinear displacement distribution of the semi-infinite strip–Application to deformable rocking bodies.” International Journal of Solids and Structures, 170, 22-37.
3. Avgenakis E. and Psycharis I.N. (2020) “Modeling of inelastic rocking bodies under cyclic loading.” Journal of Engineering Mechanics 146(4): 04020020.
4. Avgenakis E. and Psycharis I.N. (2020) “An integrated macroelement formulation for the dynamic response of inelastic deformable rocking bodies.” Earthquake Engineering and Structural Dynamics.

RockingBC_model

I have uploaded all the necessary code and made some changes in other files needed to recognize the new element. Apart from element code, the necessary documentation and an example file are also provided.
Please inform me if there is any problem or further changes are needed.

Thank you,
Evangelos Avgenakis

### CODE REVIEW

**Comment by mhscott** [comment]
Thank you for contributing the element.  Could you remove the example scripts from the SRC/element/rockingBC directory and put them somewhere in EXAMPLES/ExampleScripts instead?

**Comment by vavgen** [comment]
Thank you for the response. I have moved the example file to the aforementioned folder. There are still some files in misc folder, containing the documentation for the element, I hope it is suitable for OpenSees Wiki without many changes. Please also link to the example file there if possible. Should I also prepare another version for the new documentation? Thank you.

**Comment by mhscott** [comment]
Hello @vavgen,
Can you fix the conflicts with this PR?
Thanks!
Michael

**Comment by vavgen** [comment]
Done!
For some reason, the changes in Win64/proj/element/element.vcxproj.filters cannot be located by GitHub.

**Comment by vavgen** [comment]
Remade the aforementioned file in order to better depict the changes in GitHub

**Comment by mhscott** [comment]
Thanks for fixing the conflict, but can you add the commands to the new documentation pages
https://github.com/OpenSees/OpenSeesDocumentation

**Comment by vavgen** [comment]
Created a PR in that repository. Thank you.

**Pull request merged**
