### PR TITLE
Fix typos in `SRC/recorder`

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Looks like there is an unrelated issue with the CI
```
WARN: Remotes registry file missing, creating default one in /home/runner/.conan/remotes.json
ERROR: Conflict in hdf5/1.12.0:
    'hdf5/1.12.0' requires 'zlib/1.2.11' while 'libmysqlclient/8.0.25' requires 'zlib/1.2.12'.
    To fix this conflict you need to override the package 'zlib' in your root package.
Error: Process completed with exit code 1.
```

**Comment by luzpaz** [comment]
Would someone be kind enough to re-run the CI on this PR ?

**Comment by lcpt** [comment]
What's the CI?

**Comment by luzpaz** [comment]
@lcpt in this case the Github Action CMake build

**Pull request merged**
