### PR TITLE
fix makefile to include SRC/damping

### PR DESCRIPTION
**Pull request by mtsonicc**
trying to update makefile
SRC/damping was missing in the previous file

### CODE REVIEW

**Comment by mtsonicc** [comment]
I have no idea why compiling keeps failing..
zlib/1.2.12 seems to have conflict with zlib/1.2.13.
Any comments or advice would be appreciated.

```
Downloading conanfile.py
[85](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:86)
Downloading conan_export.tgz
[86](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:87)
zlib/1.2.12: Downloaded recipe revision 0
[87](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:88)
WARN: Remotes registry file missing, creating default one in /home/runner/.conan/remotes.json
[88](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:89)
ERROR: Conflict in tcl/8.6.10:
[89](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:90)
    'tcl/8.6.10' requires 'zlib/1.2.12' while 'hdf5/1.12.0' requires 'zlib/1.2.13'.
[90](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:91)
    To fix this conflict you need to override the package 'zlib' in your root package.
[91](https://github.com/OpenSees/OpenSees/actions/runs/3484771936/jobs/5829669755#step:4:92)
Error: Process completed with exit code 1.
```

**Comment by mhscott** [comment]
@mtsonicc How is this change to Makefile a pull request? The SRC/damping directory is already there, so this PR is not necessary Are you pushing from an unforked repo? Do you merge changes from upstream? In my limited knowledge of GitHub, this PR seems unusual that you were allowed to make this PR in the first place.

**Comment by mtsonicc** [comment]
@mhscott Thank you for your reply.
Yes I do understand that `SRC/damping` is already there for the case of `$RELIABILITY` is `YES`.
But for the case of `$RELIABILITY` is `NO`, `SRC/damping` is not there.
That is why I put SRC/damping in that line.
Without that line, I kept failing to compile OpenSees in Ubuntu 22.01 WSL with `$RELIABILITY` is `NO`.

Am I doing something wrong? Is `SRC/damping` not allowed if `$RELIABILITY` is `NO`?

p.s. I forked the source codes from the most recently available ones from master branch.

**Comment by mhscott** [comment]
@mtsonicc I see. Sorry about that, I only looked at the diffs and the PR description which didn't have the context.

**Comment by mtsonicc** [comment]
@mhscott No problem. I forgot to write down description for making such changes.
Thank you for accepting this merge request.

**Pull request merged**
