### PR TITLE
Add new Series3D Material Wrapper

### PR DESCRIPTION
**Pull request by MassimoPetracca**
@fmckenna @mhscott @jaabell 

This PR adds a new Series3D material wrapper (A Series wrapper for 3D materials, with the option to give custom weights for each sub-material):

image

Documentation and Examples coming soon

### CODE REVIEW

**Comment by jaabell** [comment]
Hi @MassimoPetracca . Thanks. Since the Ubuntu bundled build is failing, I manually checked that this compiles under linux. Merging.

**Comment by mhscott** [comment]
@jaabell We typically don't merge new models until there is an accompanying PR for documentation. I suppose you or @MassimoPetracca will take care of that?

**Comment by MassimoPetracca** [comment]
Dear @mhscott, sure I'm already taking care of that as I wrote in the PR. documentation and examples in tcl and python are ready. I just need to write some last equation and I'll do the PR in the weekend.

**Comment by MassimoPetracca** [comment]
Here's the documentation OpenSees/OpenSeesDocumentation#71

**Pull request merged**
