### PR TITLE
fix last pull requests

### PR DESCRIPTION
**Pull request by imeg**
after last commit pull requests to master some errors happens

### CODE REVIEW

**Comment by imeg** [comment]
"<<<<<<< HEAD" ???

**Comment by mhscott** [comment]
I hope all of this gets sorted out soon!

I assume that most of this commit (everything besides the EQPath source files) will be reverted by @fmckenna.  To support OpenSees.net, I recommend you look in to maintaining a fork of the OpenSees/OpenSees github repository.  The project files and source files for .net should not be in the main repository.

**Comment by sewkokot** [comment]
Thank you @imeg for your contributions. However, I would like to advise you to use 'squashing' commits and avoid meaningless commit names such as "f1", "aaaqw" or "Test" (from September 8th and 9th). Such commit names should not land in the main OpenSees repository because the commit history gets sloppy and this will create problems when debugging in the future.

For help on git squashing see e.g.:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History or
https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/

**Comment by imeg** [comment]
Dear Prof. Scott, Dr. McKenna,
I understand that there are many contributions made to OpenSees and it takes much time to check and respond to contributors. I would like to emphasize that .NET wrappers enhance the use of OpenSees in variety of environments like MATLAB, Python, Grasshopper, etc. This achievement is done by +100k lines of C++/CLI codes that I've developed and submitted to GitHub repository. I have expended plenty of time developing and verifying these wrappers and I take the responsibility of their correctness. Since the .NET wrapper is fully compatible with OpenSees sourse, I would be grateful if you support .NET and give me and other GitHub users the motivation to continue extending OpenSees. I appreciate all the efforts for developing, checking and maintaining the OpenSees source.
With sincere regards,
M. Salehi

**Comment by imeg** [comment]
Dear @sewkokot
Unfortunately a few days ago my account at GitHub was limited due to US sanctions and I do not have access to my private OpenSees projects. The main reason for these problems is this. I've moved my private projects to another location. In the future, such mistakes will certainly not occur.

GitHub message :
"Due to U.S. trade controls law restrictions, your GitHub account has been restricted. This means we have suspended access to private repository services and paid services for your account. For free individual accounts, you still have access to free GitHub public repository services (such as public repositories for open source projects and associated GitHub Pages and Gists). If you believe your account has been flagged in error, and you are not located in or resident in a sanctioned region, please file an appeal. Please read about GitHub and Trade Controls for more information."

**Pull request merged**
