### PR TITLE
Fixing SRC/Makefile for PML

### PR DESCRIPTION
**Pull request by parduino**

### CODE REVIEW

**Comment by aschellenberg74** [comment]
Hey Pedro,
If you have a chance, could you please add the debug version of the PML.lib to the Win64 project and add the debug and release versions of the PML.lib to the Win32 project?
Thanks a lot,
Andreas

**Comment by mhscott** [comment]
Andreas,

I get a compile error on Linux related to (not enough) constructor arguments.

[cid:1f9e974d-4fc0-4b7d-8027-a07df23c0377]

Should TclAdapterCommand.cpp be compiled?  It looks like you're using the OPS_ functions.

Thanks,

Michael
________________________________

**Comment by parduino** [comment]
Hi Mike

Hope this is not related to PML... Let me know if it is.
And yes, we should add the PML.libs for the debug a X32 VS solution files.

Pedro

Sent from my iPhone

On Jan 20, 2021, at 6:22 AM, Michael H. Scott <notifications@github.com> wrote:

﻿

Andreas,

I get a compile error on Linux related to (not enough) constructor arguments.

[cid:1f9e974d-4fc0-4b7d-8027-a07df23c0377]

Should TclAdapterCommand.cpp be compiled? It looks like you're using the OPS_ functions.

Thanks,

Michael
________________________________

**Comment by mhscott** [comment]
Sorry, Pedro, I replied to the wrong thread.  Not related to PML!

**Comment by aschellenberg74** [comment]
Hi Michael,

Let me check later today.
Yes, I am using the OPS_ function.

Andreas

**Comment by mhscott** [comment]
I already fixed it :)  The Tcl files for the adapter/actuator elements are not linked anywhere, so removing them from the Makefile was all that was needed.

https://github.com/OpenSees/OpenSees/commit/5125ce5bd20de44da278c436b36f8f284e9aa4c9

**Comment by aschellenberg74** [comment]
Thanks Michael. Awesome!

**Pull request merged**
