### PR TITLE
Add missing line

### PR DESCRIPTION
**Pull request by mckee107**
Had error where transfTag was always getting kicked back as non-existent. Discovered missing numData = 1; line when compared to elasticBeamColumn2d element

### CODE REVIEW

**Comment by mhscott** [comment]
These changes appear to be only for your local branch and are not suitable for the main branch.

**Comment by mhscott** [comment]
I think PR #214 was all you meant to push to main branch.  Thanks for catching the error!

**Comment by mckee107** [comment]
Yes, that is all I meant to push.  I don't know how the others were pushed
as well.  Thanks!


--


*Codi D. McKee*
Graduate Research Assistant
Texas A&M Engineering Experiment Station
Zachry Department of Civil and Environmental Engineering
Texas A&M University
College Station, TX 77843-1228

mobile: 585.331.7787 | cmckee@tamu.edu
- - - - - - - - - - - - - - - - - - - - - - - -
*TEXAS A&M UNIVERSITY* | FEARLESS on Every Front

**Comment by mhscott** [comment]
Once you make a pull request, all of your subsequent commits to your local branch get sucked in until the PR is merged or closed.  The best way to deal with this is through the use of branches ... I'm still trying to figure them out myself :)

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://cce.oregonstate.edu/scott>
OpenSees blog: portwooddigital.com<http://www.portwooddigital.com/>
________________________________

**Pull request closed without merging**
