### PR TITLE
Adding E-SFI-MVLEM-3D

### PR DESCRIPTION
**Pull request by kkolozvari**
This PR includes addition of the E_SFI_MVLEM_3D element, which is a 3D macroscopic shear-flexure-interaction element for nonlinear analysis of RC walls with non-rectangular cross section. This model is an EFFICIENT version of the previously implemented SFI-MVLEM-3D element.  

Information about model formulation and validation can be found here https://doi.org/10.1016/j.engstruct.2023.116700

User documentation can be accessed from here https://kkolozvari.github.io/E-SFI-MVLEM-3D/

### CODE REVIEW

**Comment by mhscott** [comment]
@kkolozvari Build failed. Please check the details and push a fix.

**Comment by mhscott** [comment]
@kkolozvari Also, please add documentation to github.com/OpenSees/OpenSeesDocumentation

**Comment by kkolozvari** [comment]
@mhscott it build OK on my computer. Can you please take a look at the "Files changed" and let me know if additional library that I added to "Win64/proj/openSees/OpenSees.vcxproj" (last file) can cause this issue? If yes, I will revert this file to the previous version. Thank you.

Regarding the user docs, I will add it shortly. Currently, user docs are available at https://kkolozvari.github.io/E-SFI-MVLEM-3D/

**Comment by mhscott** [comment]
@kkolozvari check the auto build. Click the red x

**Comment by kkolozvari** [comment]
@mckee107 I don't recall having to update this file the last time I added a new element (2 years ago), so I missed it. Thanks for letting me know. I have made the necessary changes. 
@mhscott it appears the build was successful after fixing the issue. Please let me know if there is anything else. Thank you.

**Comment by mhscott** [comment]
@kkolozvari Thanks. Will wait for the docs at OpenSeesDocumentation. You don't have to add much, just the following:
+ brief summary of the element
+ Python and Tcl commands
+ Link to your docs page

**Comment by kkolozvari** [comment]
@mhscott I just created a PR for the user documentation. Please let me know if there is anything else. Thanks.

**Pull request merged**
