### PR TITLE
New Soil Material

### PR DESCRIPTION
**Pull request by sebmagia**
Hello,

I just uploaded a new soil material for simulating the behavior of coarse-grained granular soil during seismically-induced liquefaction, developed by Zhijian Qiu. The files were not created by me. It is my first pull request to OpenSees, and I have no experience using cpp, so hopefully, this request is adequate.

### CODE REVIEW

**Comment by mhscott** [comment]
Please provide documentation for the model at github.com/OpenSees/OpenSeesDocumentation

**Comment by mhscott** [comment]
Do you have permission from the authors of these .cpp and .h files to include the models in the OpenSees repo. There is a non-standard copyright statement in the .cpp file.

**Comment by fmckenna** [comment]
still awaiting documentation.

**Comment by sebmagia** [comment]
I'm not experienced enough in opensees and cpp to assess if what I implemented is correct. I'm closing the request

**Pull request closed without merging**
