### PR TITLE
New triple FP isolator element (TripleFrictionPendulumX)

### PR DESCRIPTION
**Pull request by shocky0424**
Dear OpenSees administrators,

Please consider the pull request for the TripleFrictionPendulumX element object, which is an extension of the TripleFrictionPendulum element capable of accounting for heating effects on the frictional behavior of triple friction pendulum isolators. The horizontal behavior of the element is achieved by the series model, which consists of properly combined hysteretic/frictional and multidirectional gap elements.

Three main modifications in the TripleFrictionPendulumX element include: 1) computation of the displacement and velocity histories at each of the four sliding interfaces of the isolator, 2) computation of the temperature history at each sliding interface, and 3) accounting for the dependency of the coefficient of friction on the instantaneous temperature at each sliding interface.

Exemplary documentation(which will be pull-requested in OpenSeesDocumentation) can be seen via the link below:

https://openseesdocumentation.readthedocs.io/en/latest/user/manual/model/elements/TripleFrictionPendulumX.html

Please let me know if you have any questions or concerns about the element.

### CODE REVIEW

**Comment by mhscott** [comment]
Thanks, but you only added the source code. Please add the following:
+ Tcl command
+ Python command
+ classTags.h
+ FEM_ObjectBroker_AllClass.cpp

**Comment by shocky0424** [comment]
I included all the items except for the Python command. I'm not familiar with how to prepare the Python command for OpenSeesPy since I haven't used it before. If the Python command is necessary to implement the new element in OpenSees, I'll try to prepare it, regardless of the time it may take.

**Comment by mhscott** [comment]
Looks like you didn't add the element to TclElementCommands.cpp.

You have the OPS_TFPX function in the TFPX.cpp file, so it should be straightforward to add to SRC/interpreterOpenSeesElementCommands.cpp for Python

**Comment by shocky0424** [comment]
I updated five cpp files (TclElementCommands.cpp, OpenSeesElementCommands.cpp, GmshRecorder.cpp, PVDRecorder.cpp, and VTK_Recorder.cpp).

**Comment by shocky0424** [comment]
I just uploaded the Python command("TripleFrictionPendulumX.py") in "EXAMPLES/ExamplePython" . It is working on my machine. Please let me know if any issues arise from the command.

**Pull request merged**
