### PR TITLE
correct startTime implementation for PathSeries

### PR DESCRIPTION
**Pull request by mckee107**
Add startTime to PathSeries constructors. Add getStartTime() virtual function to TimeSeries and add default behavior to affected time series files.

For Tcl interpreter, users could specify `-startTime`, but the `PathSeries` constructors did not use the value.

### CODE REVIEW

**Comment by mhscott** [comment]
@mckee107 Thanks! One suggestion - you can define the default `return 0.0;` behavior in the TimeSeries base class. Since the method is virtual, subclasses can override.

```cpp
virtual double getStartTime () {return 0.0;}
```

**Comment by mhscott** [comment]
@mckee107 Some of the time series, e.g., `Pulse`, `Rectangular`, `Trig`, `Triangle`, already have start times as private data, but you return 0.0 for `getStartTime()`.

**Comment by mckee107** [comment]
Interesting... I don't know how I overlooked that. Fixed it.

**Comment by mckee107** [comment]
> I'm curious why you removed this `delete` statement.
> 
> image

It appears to be an innocent bystander from merging the upstream repo into my fork before submitting the pull request. I will go through the changes again to make sure nothing else was overlooked

**Pull request merged**
