### PR TITLE
New Isogeometric analysis capabilities

### PR DESCRIPTION
**Pull request by jaabell**
Dear OpenSees community, 

I'm excited to announce that I'm adding new capabilities to OpenSees (py): [isogeometric analysis](https://en.wikipedia.org/wiki/Isogeometric_analysis) (IGA) modeling for curvilinear shells. IGA is very similar to FEM with some key differences: notably the use of [NURBS](https://en.wikipedia.org/wiki/Non-uniform_rational_B-spline) as functional basis which makes it possible to have high inter-element derivative continuity at the expense of losing some of the non-overlapping of element domains (notion of "element" gets a bit fuzzy). 

This new code basically implements:

- An IGA "surface patch" (`IGASurfacePatch`), which is sort of a macro-element, as a subclass of SubDomain to coordinate computations within a patch. 
- A new (variable order) shell element (`IGAKLShell`) based on large-deformation Kirchoff-Love shell theory for use with the patch class. 
- A bunch of new `nDMaterial`s for modeling of composite plane-stress materials, including capabilities for fatigue analysis (`ElasticPlaneStress`, `ElasticOrthotropicPlaneStress`, `VonPapaDamage`). 

The code plays well with [geomdl](https://pypi.org/project/geomdl/) library for NURBS modeling directly in python. There is a TCL interface too, but all the IGA stuff would have to be pre-processed elsewhere. 

Felipe Elgueta (@felgueta1995), my MS student who is the main implementer of this code, spent a lot of time testing, debugging and optimizing the new code I'm introducing. There is a suite of shell benchmarks that I'll make available to everyone as soon as we clean it up (or if you really can't wait check out the very dirty examples repo at [https://github.com/jaabell/OpenSees-IGA-Examples](https://github.com/jaabell/OpenSees-IGA-Examples)... the KLShell forlder is what you want to look at). His code can solve many fancy large-displacement cases with all sorts of crazy nonlinear behavior and even material orthotropy! 

I've also fully switched into the CMake build scheme, so I've added the changes to the CMake build system. It builds on linux with cmake. I'll wait a bit before merging the pull request into main opensees, just to see if people want to play around with it or there are any issues that pop up. 

There is an MS thesis documenting in depth all the development, as well as an application paper. Due to the publication (and the thesis) needing to be accepted before distribution I can't share these publicly yet, but if you contact me I can send these privately to you so you can get started if you find this exciting!

### CODE REVIEW

**Comment by jaabell** [comment]
Hi @mhscott, I want to push this code in. It touches several parts of OpenSees thats why I was waiting maybe for a review by Frank. Also, the compilation on windows is not taken care of, I don't know if it is possible from linux. 

Can you please give me indications? Or should I just do the merge? I don't want to mess up on this, causing headaches to others. 

Thanks!

**Comment by mhscott** [comment]
No, please DO NOT merge, especially considering all the issues you brought up! @fmckenna is reviewing.

**Comment by jaabell** [comment]
> No, please DO NOT merge, especially considering all the issues you brought up! @fmckenna is reviewing.

Lol. By "issues you brought up" do you mean the ones stated on the comment or past ones?

**Comment by fmckenna** [comment]
it's just the windows projects. i need to update them so merge does not break the windows build. however, i also want tp remove visual studio all together and so my efforts are elsewhere as i try and resolve that. trouble i am having is with intels one api and windows compilation. if can get past that i will be removing all windows projects and tell people only way to build on windows is using cmake and the free intel compiler.

**Comment by jaabell** [comment]
> it's just the windows projects. i need to update them so merge does not break the windows build. however, i also want tp remove visual studio all together and so my efforts are elsewhere as i try and resolve that. trouble i am having is with intels one api and windows compilation. if can get past that i will be removing all windows projects and tell people only way to build on windows is using cmake and the free intel compiler.

Thanks Frank. Its cool that OpenSees moved to cmake which is so nice. Its the biggest thing since moving to github in my opinion. Will make developing new stuff, and bringing in new talent much easier. 

Regarding the merge. You'll check that later and do the merge?

**Comment by mhscott** [comment]
Yeah, I meant don't knowingly break the windows build with 50+ new source files.
________________________________

**Comment by mhscott** [comment]
Thanks for taking care of the Visual Studio projects!

**Comment by jaabell** [comment]
> Reference in ne

You´re welcome! But, I wouldn't have it any other way. I can't take credit, though. It was @MassimoPetracca that did that part to make sure I don't break everyone's work.

**Pull request merged**
