### PR TITLE
Typo fixes for DEVELOPER/ and SRC/element/

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../opensees-word-whitelist.txt --skip="./OTHER"

### CODE REVIEW

**Comment by luzpaz** [comment]
Devs, which directories are 3rd party libs/files that I should omit fixing typos on ?

**Comment by jaabell** [comment]
The OTHER directory contains 3rd party libs.

José A. Abell, Ph.D. (from mobile phone)

**Comment by luzpaz** [comment]
@jaabell do you want all the typos in one PR or split them up ?

**Comment by fmckenna** [comment]
thanks

**Comment by jaabell** [comment]
> @jaabell do you want all the typos in one PR or split them up ?

I don't think I know whats going on with what you're doing. So I don't know. :)

**Pull request merged**
