### PR TITLE
GI Element's Python Command Update

### PR DESCRIPTION
**Pull request by msalehi2004**
Hello Michael,

Here I have only made changes to the GI element commands.

Thanks,
Mohammad

### CODE REVIEW

**Comment by mhscott** [comment]
Your changes revert changes made earlier today. https://github.com/OpenSees/OpenSees/commit/60d0e79d6b2717cefd201715ff2d22b101071694
Please make sure you are always working with the latest code, i.e., pull from upstream, merge branches, etc.

**Comment by msalehi2004** [comment]
Sorry, I wasn't aware of those changes. I just got those back.

**Comment by mhscott** [comment]
Thanks. I know it's not a big deal in this case, but it looks like you manually re-did the changes from earlier today. (I can tell by the spacing). It would be better to use git commands. Imagine if you had to re-do multiple lines of code...

**Comment by msalehi2004** [comment]
> Thanks. I know it's not a big deal in this case, but it looks like you manually re-did the changes from earlier today. (I can tell by the spacing). It would be better to use git commands. Imagine if you had to re-do multiple lines of code...

You are right :) - it was a minor change so I did it manually!

**Pull request merged**
