### PR TITLE
CYPE Software: OpenSeesSP for Win64 project update

### PR DESCRIPTION
**Pull request by mfernba**
This PR updates OpenSeesSP project files for building in Windows 64 bit version. OpenSeesSP has been tested using MUMPS as solver only.

It also adds MUMPS 5.4.0 Visual Studio Project to OTHER folder that compiles if you have installed Intel OneAPI BaseKit (MKL libraries) + Intel OneAPI HPC Kit (MPI, Fortran Compiler).

The MPI header routes have been changed to the default installation of Microsoft MPI 10.1.2 (this only affects visual studio projects). Also, MUMPS include file paths have been updated to the MUMPS 5.4.0 distribution I added before in the needed project files, no source code changes made.

The Windows Solution project has been modified to include distributedsuperlu, openseessp and parallel projects, by their are disabled from building in the configuration manager. Enabling them for Debug/Relase in Win64 will work but will ask for several new libraries. 

The MUMPS libraries needed will be generated by the MUMPS solution and need to be copied (by now) to debug / release folder in lib folder of the Win64 build. These are: dmumps_c.lib, dmumps_fortran.lib, mumps_common_c.lib, pord_c.lib.

Additionally, linker will also ask for:

mkl_intel_lp64.lib
mkl_intel_thread.lib
mkl_core.lib
mkl_blacs_msmpi_lp64.lib
mkl_scalapack_lp64.lib
libiomp5md.lib

msmpi.lib
msmpifec.lib

MKL libraries + libiomp5md must be get from Intel OneAPI installation dir for x64 and copied to lib folder (simply perform a search in this Intel OneAPI installation folder to locate them, be sure to pick the x64 version).

msmpi and msmpifec are added through additional path libraries on the visual studio project so there is no need to copy them.

### CODE REVIEW

**Comment by mhscott** [comment]
Muchas gracias! Thank you so much for taking the time to do this and to give back to the community!

Would you mind sending @fmckenna and me a minimum working example script so that we can check out the branch and test it out?

**Comment by mfernba** [comment]
Hi @mhscott, @fmckenna :

Here I attach a simple test that Jinchi Lu send me a few years ago: [shearbeam.tcl.zip](https://github.com/OpenSees/OpenSees/files/6663330/shearbeam.tcl.zip)

Before executing, be sure that  libiomp5md.dll for x64 is located in the same folder as OpenSeesSP.exe. This is required by MUMPS because it is compiled using OpenMP.

Use the syntax "mpiexec -n 2 OpenseesSp.exe shearbeam.tcl" to test it. 

It gives the same results as sequential Opensees using mumps (I have a version that can also use MUMPS, in fact, I think we could add the compiled libs of MUMPS to the lib folder and enable mumps for sequential analysis) .

If you use Intel MPI you'll see a message about a stack corruption problem that MS-MPI doesn't show. 
I will add the solution for this in another PR. I'm proceeding in small batches, we have several things that I would like to add to main Opensees repo that could be useful  for others.

Let me know any problem you encounter.

Thanks.

**Comment by Chenshupei95** [comment]
hi @mfernba:
 I noticed that in your model "shearbeam.tcl", there is no initial state analysis, i.e. the InitialStateAnalysis command, when I use teh InitialStateAnalysis command to analysis a large model, the analysis was failed due to error as follow:
"MPI_Channel::recvID() - incorrect number of entries for ID received: 1 exptected: 4
ShadowSubdomain::revertToStart ERROR ERROR"
I want to know that have you ever seen the error, and did you fix it?
much thanks.

**Comment by mfernba** [comment]
> hi @mfernba:
> I noticed that in your model "shearbeam.tcl", there is no initial state analysis, i.e. the InitialStateAnalysis command, when I use teh InitialStateAnalysis command to analysis a large model, the analysis was failed due to error as follow:
> "MPI_Channel::recvID() - incorrect number of entries for ID received: 1 exptected: 4
> ShadowSubdomain::revertToStart ERROR ERROR"
> I want to know that have you ever seen the error, and did you fix it?
> much thanks.

I think the problem is related to some of the material objects you are using. If you send me a .tcl file which execution raises the problem, I'll try to look at it as soon as posible.

**Comment by mhscott** [comment]
Please move the shearbeam.tcl conversation to a new thread.

**Comment by mhscott** [comment]
@fmckenna bump

**Comment by fmckenna** [comment]
the instructions for cmake pull in mumps and generate SP and MP. the win project files are going away soonest. thanks for helping out but we wanted to get the cmake working w/o adding new requirements.

**Comment by mfernba** [comment]
No problem, I understand the reasons. cmake is the right choice for a multiplatform project as OpenSees and the transition to a new build system is far from easy. I'll study the cmake building system to stay current in OpenSees development.

Thanks!

**Pull request closed without merging**
