### PR TITLE
Typo fixes for SRC/domain, SRC/reliability, SRC/system_of_eqn

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../opensees-word-whitelist.txt --skip="OTHER"`

### CODE REVIEW

**Comment by sa-jalali** [comment]
Soon, you will have the largest number of contributed commits by correcting comment typos. Even more than @mhscott or @fmckenna  :)

**Comment by mhscott** [comment]
We'll be sure to exclude these commits when we distribute the royalties from OpenSees :)

**Comment by luzpaz** [comment]
Obviously that's not my intention :stuck_out_tongue_winking_eye:  
Just wanting to support this effort in my own way

**Comment by luzpaz** [comment]
JFYI, one more PR after this and we should be done.

**Pull request merged**
