### PR TITLE
Another mesh type used for 3D PFEM 

### PR DESCRIPTION
**Pull request by zhuminjie**

### CODE REVIEW

**Comment by fmckenna** [comment]
@zhuminjie you need to fix the build issue.

**Comment by zhuminjie** [comment]
Yeah, the build error is like the following, there are many of them but similar

/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpython3.8.a(getcompiler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

Do you have any idea what they are?

**Comment by mhscott** [comment]
@fmckenna Is `-fPIC` enabled in the CMake settings?

**Comment by zhuminjie** [comment]
There is nothing special here. How about I close this one and resubmit again.

**Pull request closed without merging**
