### PR TITLE
Changing std::vector initialization

### PR DESCRIPTION
**Pull request by mhscott**
Changing std::vector initialization for strict ansi compiler

### CODE REVIEW

**Comment by ahartloper** [comment]
@mhscott Hi Micheal, for my own information, can you let me know more specifically what the issue was? To my knowledge, the initialization should be according to C++ standard. After I can check the other code I wrote. Thanks, Alex.

**Comment by mhscott** [comment]
@ahartloper The code did not compile on Mac OS. There may also be some other small changes related to using opserr instead of cerr.  opserr should be used so that output gets redirected to the right place, e.g., in a Jupyter Notebook, cerr will go nowhere but opserr will be seen in the Notebook.

**Comment by ahartloper** [comment]
OK, thank you for the reply. I'll look to compile OpenSees on my Mac as well to test there. The cerr info is good to know, I'll look to change all the std::cerr and std::cout to opserr.

**Comment by ahartloper** [comment]
@mhscott I confirmed that this is a C++11 compatibility issue. This can be verified by passing the `-std=c++11` flag to g++ in the Makefile.def (default is C++98 as far as I can tell).

I agree it's best to leave the material with the changes you made for now, but using an updated version of C++ could be something to consider in the future.

**Pull request merged**
