### PR TITLE
Fix getRetainedNodes and getConstrainedNodes commands

### PR DESCRIPTION
**Pull request by sewkokot**
This PR is to fix https://github.com/OpenSees/OpenSees/issues/1068
@BijanSeif, I have tested it with your MWE, but more testing would be welcome.

### CODE REVIEW

**Comment by BijanSeif** [comment]
Again Thanks, Dr. @sewkokot.
As I understood, for OpenSees the equalDOF and RigidDiaphragm and RigidLink are same and define constrained and retained nodes (Correct me if I'm wrong).
So OpenSees do not record the type of command that nodes are retained or constrained to each other. I mean that we can't understand that nodes are constrained and retained to each other by Rigidlink or by equalDOF or by RigidDiaphragm while it is important to distinguish Rigidlink case from the other cases. (For plotting purposes, it is necessary to show the rigidlinks but for other cases is not)
let me know your idea and also guide me if there is a way to distinguish it.

Thanks.

**Comment by sewkokot** [comment]
@BijanSeif, You can read more on this subject in https://github.com/OpenSees/OpenSees/issues/729
and in particular the ideas by @ambaker1 in https://github.com/OpenSees/OpenSees/issues/729#issuecomment-992756226

The MP constraint matrix can be displayed, for instance, using `ops.printModel()`.

However those ideas have not been implemented yet.

**Comment by BijanSeif** [comment]
Dear @sewkokot 
I got my answers from your complete conversation. I would like to know that what happened about "getMPType"? "getMPType" is exactly what I am searching for? Could you add it to OpenSees? 
you said "However those ideas have not been implemented yet" 
is there any limitation for this purpose? or just finding free time!

**Comment by sewkokot** [comment]
@BijanSeif, Adding the `getMPType` command would require more modifications in OpenSees source code than providing the `getConstraintMatrix` output command which then could be used to identify the MP type. I'm implementing the `getConstraintMatrix` now, and will see if it's enough for the purpose of opsvis. 

Also, there are limitations in Matplotlib to develop custom markers for OpenSees elements (equalDOF, rigidLink and RigidDiaphragm). And I simply need more free time to work on these features :)

**Comment by BijanSeif** [comment]
Again, thanks dear Dr. @sewkokot for the answer.

**Comment by BijanSeif** [comment]
Hi 
The above commands are working correctly in OpenSeesPy. I know that users should wait for OpenSees.exe release till use them in TCL 

But

getRetainedNodes AND getConstrainedNodes commands seems are not available for TCL commands!

**Pull request merged**
