### PR TITLE
Uncomment the parsers for Joint2D/3D and fix the constructors.

### PR DESCRIPTION
**Pull request by ahartloper**
Fixes the issues that I made with PR #280.

### CODE REVIEW

**Comment by ahartloper** [comment]
> Continuing the discussion from #280, why use a std::vector for DamageModels and not UniaxialMaterials? 

This was just part of my problem solving process: testing and fixing the bug, then thinking about how it could be done better the next time.

> Why not keep it simple (and presumably more portable) by using pointer arrays for both sets of objects instead of std::vector for one and not the other?

Hmm, I never thought about using arrays since to me the vector is generally simpler because of iterators (plus their other features). In my opinion they are both equally portable since it's part of the standard library.

**Comment by mhscott** [comment]
It looks like it's a fixed number of DamageModels, so iterators don't buy you much.  Plus, some folks still have issues with the new standard library.  I think it's always best to not use standard libraries unless absolutely necessary.  That does not appear to be the case here.

**Comment by ahartloper** [comment]
> It looks like it's a fixed number of DamageModels, so iterators don't buy you much. Plus, some folks still have issues with the new standard library. I think it's always best to not use standard libraries unless absolutely necessary. That does not appear to be the case here.

Yes true. Fair enough, I can make the change no problem.

**Comment by ahartloper** [comment]
@mhscott See the latest commit for my proposed changes and let me know what you think :) .

**Pull request merged**
