### PR TITLE
Added missing SAniSandMS to OpenSeesPy.

### PR DESCRIPTION
**Pull request by millen1m**
Also reduced verbose output on initialization.

Test (fails without these changes):

import opensees as opy
opy.wipe()
opy.model('basic', '-ndm', 2, '-ndf', 3)
opy.nDMaterial('SAniSandMS', 3, 1110.0, 0.05, 0.72, 1.27, 0.712, 0.049, 0.845, 0.27, 101.3, 0.01, 5.95, 1.01, 2.0, 1.06, 1.17, 0.0005, 260.0, 1, 1.6, 1, 1, 1, 0, 1, 1e-07, 1e-07)

### CODE REVIEW

**Comment by millen1m** [comment]
I am not sure why this caused a failure - error related to reliability. Any advice would be helpful.

/home/runner/work/OpenSees/OpenSees/SRC/interpreter/OpenSeesParameterCommands.cpp:51:3: error: ‘ReliabilityDomain’ was not declared in this scope
   51 |   ReliabilityDomain *theReliabilityDomain = OPS_GetReliabilityDomain();
      |   ^~~~~~~~~~~~~~~~~
/home/runner/work/OpenSees/OpenSees/SRC/interpreter/OpenSeesParameterCommands.cpp:51:22: error: ‘theReliabilityDomain’ was not declared in this scope
   51 |   ReliabilityDomain *theReliabilityDomain = OPS_GetReliabilityDomain();
      |                      ^~~~~~~~~~~~~~~~~~~~
/home/runner/work/OpenSees/OpenSees/SRC/interpreter/OpenSeesParameterCommands.cpp:51:45: error: ‘OPS_GetReliabilityDomain’ was not declared in this scope
   51 |   ReliabilityDomain *theReliabilityDomain = OPS_GetReliabilityDomain();
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~
[ 17%] Building C object OTHER/SuperLU_5.1.1/CMakeFiles/DLUSRC.dir/SRC/dlangs.c.o
make[2]: *** [CMakeFiles/OPS_INTERPRETER.dir/build.make:244: CMakeFiles/OPS_INTERPRETER.dir/SRC/interpreter/OpenSeesParameterCommands.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by mhscott** [comment]
Do you get the errors with make instead of cmake?

**Comment by millen1m** [comment]
I wasn't getting any errors using make on MacOS but wasn't building with reliability flag. The error that I copied in was from the conan cmake build.

**Comment by mhscott** [comment]
cmake could be missing _RELIABILITY ... we haven't quite sorted that out

**Pull request merged**
