### PR TITLE
Gradient Inelastic Beam-Column Element Implementation 

### PR DESCRIPTION
**Pull request by msalehi2004**
Dear Prof. Scott (or Dr. McKenna),

I have added a number of files to my forked OpenSees respiratory which contain the 2D and 3D versions of the gradient inelastic beam-column element formulation and Simpson's integration rule. I have tried building the current respiratory on my computer and it works fine. Could you please check it out and apply the changes to the public respiratory in case you approve it?

I have attached the GI element command description and 2D and 3D example models that would allow you to try the element formulation. Please let me know if there is any issue or you have any questions.

Thanks for your help with this!

Best regards,
Mohammad
[Gradient Inelastic Beam-Column.zip](https://github.com/OpenSees/OpenSees/files/4062150/Gradient.Inelastic.Beam-Column.zip)

### CODE REVIEW

**Comment by fmckenna** [comment]
As we require the code be suitable for any number of different interpreters, currently limited to Python and Tcl, the code to read the command from the args needs to be redone w/o using tcl commands .. a while ago we created a new API for new elements, materials, or whatever to parse the interpreter command line .. the code in the DEVELOPER section shows examples of using this, many of elements and materials in SRC directory are using this .. you need to revise your code to use this (basically remove the Tcl**.cpp file and put a function OPS_***in the ele.cpp file.

**Comment by msalehi2004** [comment]
Hello Dr. McKenna,

Thank you very much for reviewing my files and letting me know about the
required modification. I will follow your instructions to change my element
source codes and will remove the TclCommand file.

Best regards,
Mohammad

On Fri, Jan 24, 2020 at 12:43 PM Frank McKenna <notifications@github.com>
wrote:

> As we require the code be suitable for any number of different
> interpreters, currently limited to Python and Tcl, the code to read the
> command from the args needs to be redone w/o using tcl commands .. a while
> ago we created a new API for new elements, materials, or whatever to parse
> the interpreter command line .. the code in the DEVELOPER section shows
> examples of using this, many of elements and materials in SRC directory are
> using this .. you need to revise your code to use this (basically remove
> the Tcl**.cpp file and put a function OPS_***in the ele.cpp file.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenSees_OpenSees_pull_200-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALICO2RHIWB3MSCFIXU2PULQ7MZFZA5CNFSM4KG3DDK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ3WXIA-23issuecomment-2D578251680&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=fh4P87t3rlqejwLkYoCgBY-Pl2mZEAn18l_JQG13IqY&m=zDpXd_Q6IpyEzYpjjQ8gvjmd13jjnYG_LCZpTCIo0RM&s=8K_MTgQWtsDZRJiuzE590rs0ihm6kEC0E3JWv7Noff0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALICO2WYKJHKJ5XX3TKOKYTQ7MZFZANCNFSM4KG3DDKQ&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=fh4P87t3rlqejwLkYoCgBY-Pl2mZEAn18l_JQG13IqY&m=zDpXd_Q6IpyEzYpjjQ8gvjmd13jjnYG_LCZpTCIo0RM&s=JZWvN9YhgGbbWGxbsQQH71IyFWZJPKjZ5o9ukQNoBmQ&e=>
> .
>


-- 
*Mohammad Salehi, M.S., E.I.T.*
Ph.D. Candidate in Structural Engineering
Zachry Department of Civil and Environmental Engineering
Texas A&M University

*e: * mohammad.salehi@tamu.edu
*t:  *(720) 980-4459
*w:* https://resilient-structures.com/

**Comment by msalehi2004** [comment]
Hello Dr. McKenna,

Per your instruction, I just added an OPS_* function at the beginning of my element .cpp codes to enable reading the GI element command. Even though the command arguments remained the same, I kept the TclGradientInelasticBeamColumnCommand.cpp file to be used if the Tcl interpreter is used, as is the case for some other elements (e.g. forceBeamColumn). 

Can you possibly take another look at my revised codes, build OpenSees with those, and check if I need to do anything else? It does work fine on my computer (at least when Tcl language is used).

Thank you again for your time, it is much appreciated.

Regards,
Mohammad

**Comment by fmckenna** [comment]
the changes have been pulled in .. the TclElementCommands was fixed to use the OPS commands .. will remove the TclGradentCommands when you conform it works.

**Pull request closed without merging**
