### PR TITLE
Fix the NULL dereference in Joint2D and Joint3D

### LINKED ISSUE #197: "Segmentation fault: 11" in macOS Catalina
Hello,

I'm experiencing a problem while using Joint2D in macOS Catalina.

Joint2D element requires input parameters as shown below: 
`element Joint2D $eleTag $Nd1 $Nd2 $Nd3 $Nd4 $NdC <$Mat1 $Mat2 $Mat3 $Mat4> $MatC $LrgDspTag`

If I set "$Mat1 $Mat2 $Mat3 $Mat4" to zero, OpenSees returns "segmentation fault: 11" in macOS Catalina.

an example line is shown below:
`element Joint2D 10100 10101 10102 10103 10104 10100 10101 10102 0 10104 10100 0;`

The exact same code works fine in Windows 10 (version 1903).

If I don't use zeros in "<$Mat1 $Mat2 $Mat3 $Mat4>", "segmentation fault: 11" does not happen.

example code is provided below::
[test_Joint2D.tcl.zip](https://github.com/OpenSees/OpenSees/files/4058615/test_Joint2D.tcl.zip)

Thank you for your help!

### PR DESCRIPTION
**Pull request by ahartloper**
Fixes #197 

I also auto-formatted the various Joint2D/3D files for consistency.

### CODE REVIEW

**Comment by mhscott** [comment]
It is difficult to see what you actually changed when the diffs are clobbered by the auto formatting you have done.  For future ref, please separate actual code changes and cosmetic changes in separate PRs.

Also, does the auto formatting follow some standard, or is it simply your preference?

**Comment by ahartloper** [comment]
Sure, will do. Just the Visual Studio default.

**Comment by mhscott** [comment]
Thanks.  There is not an OpenSees style guide; however, please don't advocate for whatever default Visual Studio uses ... many folks develop in Linux :)

**Comment by ahartloper** [comment]
> Thanks. There is not an OpenSees style guide; however, please don't advocate for whatever default Visual Studio uses ... many folks develop in Linux :)

As long as they don't use tabs... :P

But I can open a new pull request if you'd prefer.

**Comment by mhscott** [comment]
Then, the format you're adjusting must be old VS tab-ridden code!

**Comment by zhuminjie** [comment]
@ahartloper I wonder why do you comment out both OPS_Joint2D and OPS_Joint3D functions? Do they have any problems?

**Comment by mhscott** [comment]
Good catch, @zhuminjie.  I didn't notice with all the formatting changes :)

Maybe the issue is unfamiliarity with how to call the OPS_Joint commands from the TclModelBuiderJoint command?

**Comment by zhuminjie** [comment]
Even when I put both functions back, it has compiling errors of no matching function for constructors. Maybe revert the changes before separating the formatting and the changes?

**Comment by mhscott** [comment]
I think the constructors were changed to take UniaxialMaterial* instead of UniaxialMaterial&.  Is that why it's not matching now?

**Comment by zhuminjie** [comment]
That's the reason for the Joint3D, but for Joint2D, one of the constructions is removed.

**Comment by zhuminjie** [comment]
https://github.com/OpenSees/OpenSees/pull/280/files#diff-98a21546ed25d510b0bb5d6f4dda7f12L53-R61

**Comment by zhuminjie** [comment]
[](https://github.com/OpenSees/OpenSees/pull/280/files#diff-98a21546ed25d510b0bb5d6f4dda7f12L53-R61)

**Comment by zhuminjie** [comment]
https://github.com/OpenSees/OpenSees/pull/280/files#diff-98a21546ed25d510b0bb5d6f4dda7f12L53-R61

**Comment by mhscott** [comment]
Not sure if this is the issue, @ahartloper, but why was an std::vector used for DamageModel objects into the constructor.

**Comment by ahartloper** [comment]
My apologies, I uncommented the parsers for Joint2D and Joint3D and fixed their calls to the constructors therein. I will open a new pull request for this. My fault for not trying to compile the Python version as well to catch this issue.

@mhscott see line 904 in Joint2D.cpp to simplify the assignment and number of arguments.

**Comment by sewkokot** [comment]
Building OpenSeesPy from the up-to-date OpenSees soures gives the following error: 

`ImportError: /home/sewi/opensees_pylib/opensees.so: undefined symbol: _Z11OPS_Joint3Dv`

Is this related with this merged PR?

**Comment by ahartloper** [comment]
@sewkokot unfortunately yes, see #281 .

**Comment by mhscott** [comment]
Alright, it's merged now.  I don't get a seg fault when importing opensees.so anymore.

**Comment by sewkokot** [comment]
@ahartloper, @mhscott, I acknowledge, it's fixed now. Thank you!

**Pull request merged**
