### PR TITLE
Elemental Damping

### PR DESCRIPTION
**Pull request by yulee**
**Contribution**

1. Damping class

2. UniformDamping class - uniform damping
    
3. SecStifDamping class - secant stiffness-proportional damping

4. URDDamping class - universal rate-dependent damping

**References**

https://www.researchgate.net/publication/328827267_A_damping_model_for_nonlinear_dynamic_analysis_providing_uniform_damping_over_a_frequency_range

https://www.researchgate.net/publication/363845908_High-Performance_Uniform_Damping_Model_for_Response_History_Analysis_in_OpenSees

https://www.researchgate.net/publication/358212097_A_universal_rate-dependent_damping_model_for_arbitrary_damping-frequency_distribution

**Damping Definition**

damping Uniform $dampingTag $dampingRatio $freql $freq2 <-activateTime $Ta> <-deactivateTime $Td> <-fact $tsTagScaleFactorVsTime>

damping SecStiff $dampingTag $dampingFactor <-activateTime $Ta> <-deactivateTime $Td> <-fact $tsTagScaleFactorVsTime>

damping URD $dampingTag $numFreq $freq1 $lossFactor_1 … $freqn $lossFactor_n <-tol $Tlrnc> <-activateTime $Ta> <-deactivateTime $Td> <-fact $tsTagScaleFactorVsTime>

**Damping Application to Groups of Elements**

region $regTag <-ele ($ele1 $ele2 ...)> <-eleOnly ($ele1 $ele2 ...)> <-eleRange $startEle $endEle> <-eleOnlyRange $startEle $endEle> <-node ($node1 $node2 ...)> <-nodeOnly ($node1 $node2 ...)> <-nodeRange $startNode $endNode> <-nodeOnlyRange $startNode $endNode> <-node all> <-rayleigh $alphaM $betaK $betaKinit $betaKcomm> _<-damp $dampingTag>_

**Damping Application to Individual Elements**

element dispBeamColumn $eleTag $iNode $jNode $numIntgrPts $secTag $transfTag _<-damp $dampingTag>_

element ASDShellQ4 $eleTag $iNode $jNode $kNode $lNode $secTag _<-damp $dampingTag>_

element ShellDKGQ $eleTag $iNode $jNode $kNode $lNode $secTag _<-damp $dampingTag>_

element ShellDKGT $eleTag $iNode $jNode $kNode $lNode $secTag _<-damp $dampingTag>_

element ShellNLDKGQ $eleTag $iNode $jNode $kNode $lNode $secTag _<-damp $dampingTag>_

element ShellNLDKGT $eleTag $iNode $jNode $kNode $lNode $secTag _<-damp $dampingTag>_

element ShellMITC4 $eleTag $iNode $jNode $kNode $lNode $secTag _<-damp $dampingTag>_

element zeroLength $eleTag $iNode $jNode -mat $matTag1 $matTag2 ... -dir $dir1 $dir2 ...<-doRayleigh $rFlag> <-orient $x1 $x2 $x3 $yp1 $yp2 $yp3> _<-damp $dampingTag>_

element elasticBeamColumn $eleTag $iNode $jNode $A $E $G $J $Iy $Iz $transfTag <-mass $massDens> <-cMass> _<-damp $dampingTag>_

element forceBeamColumn $eleTag $iNode $jNode $transfTag "IntegrationType arg1 arg2 ..." <-mass $massDens> <-iter $maxIters $tol> _<-damp $dampingTag>_

element quad $eleTag $iNode $jNode $kNode $lNode $thick $type $matTag <$pressure $rho $b1 $b2> _<-damp $dampingTag>_

element stdBrick $eleTag $node1 $node2 $node3 $node4 $node5 $node6 $node7 $node8 $matTag <$b1 $b2 $b3> _<-damp $dampingTag>_

### CODE REVIEW

**Comment by fmckenna** [comment]
can you send me an email .. want to talk to you in zoom about your paper so i better understand this request

**Comment by yulee** [comment]
Thanks Frank so much. I emailed you at your berkeley.edu address and look forward to talking with you.

**Comment by yulee** [comment]
It has been a while. It would be much appreciated if you could please process this PR at your very convinience.

**Comment by mhscott** [comment]
Can this be done in the Element base class (like Rayleigh damping). It will be confusing for users because not all elements will have the uniform damping capabilities the way it is implemented in this PR.

**Comment by yulee** [comment]
Hi Michael,

    Unfortunately, it would be highly challenging for the current framework of element implementations, as explained as follows.

    The proposed damping class is more analogous to the geometrical transformation class in that it acts on the basic forces. At the moment, the naming, storage, and evaluation of basic forces and the subsequent operations on the basic forces, such as transforming to the global coordinate system, are unique to individual element formulation. For example, a linear beam element calculates the basic forces inlined with the resisting force evaluation. A nonlinear beam-column element evaluates the basic forces during internal equilibrium iteration when the trial displacement is input. A discrete element delegates the basic forces in a component-by-component manner to the sub-unidirectional material models followed by aggregation. Therefore, before a considerable effort unifying the functions associated with basic forces for all elements, the proposed damping would have to be implemented in a bespoke way for individual element formulation.

Best,
Yuli

**Comment by yulee** [comment]
Hi Michael,

    Unfortunately, it would be highly challenging for the current framework of element implementations, as explained as follows.

    The proposed damping class is more analogous to the geometrical transformation class in that it acts on the basic forces. At the moment, the naming, storage, and evaluation of basic forces and the subsequent operations on the basic forces, such as transforming to the global coordinate system, are unique to individual element formulation. For example, a linear beam element calculates the basic forces inlined with the resisting force evaluation. A nonlinear beam-column element evaluates the basic forces during internal equilibrium iteration when the trial displacement is input. A discrete element delegates the basic forces in a component-by-component manner to the sub-unidirectional material models followed by aggregation. Therefore, before a considerable effort unifying the functions associated with basic forces for all elements, the proposed damping would have to be implemented in a bespoke way for individual element formulation.

Best,
Yuli

**Comment by yulee** [comment]
x

**Comment by yulee** [comment]
We have recently published the proposed implementation of damping models. Shall we move forward and process the PR, please?

https://www.researchgate.net/publication/363845908_High-Performance_Uniform_Damping_Model_for_Response_History_Analysis_in_OpenSees

**Comment by mhscott** [comment]
You are pushing a non-trivial change to many elements. Please add examples and documentation at https://github.com/OpenSees/OpenSeesDocumentation

**Comment by yulee** [comment]
Documentation added to https://github.com/OpenSees/OpenSeesDocumentation

https://github.com/OpenSees/OpenSeesDocumentation/pull/57

**Comment by mhscott** [comment]
The Damping classes do not implement sendSelf/recvSelf methods. This will break sendSelf/recvSelf for elements that have elemental damping.

**Comment by mhscott** [comment]
Oh, I see, the damping classes do implement sendSelf/recvSelf, but only the elastic beams actually invoke these methods in their own sendSelf/recvSelf. What about all of the other elements in this PR? sendSelf and recvSelf will not work for those elements when elemental damping is used

**Comment by yulee** [comment]
sendSelf/recvSelf have been updated.

**Comment by yulee** [comment]
Thanks Frank and Michael very much!

**Pull request merged**
