### PR TITLE
removing old OpenSeesPy38 project and updating misc Win64 project settings

### PR DESCRIPTION
**Pull request by aschellenberg74**

### CODE REVIEW

**Comment by mhscott** [comment]
@aschellenberg74 Please give Frank and/or me time to test your PR before you merge.

**Comment by aschellenberg74** [comment]
Hey Mike,

Sorry about that, I had to get these changes in for Tracy's students who
are testing in the lab today.

I will definitely give you time to test next time and will not merge right
away.

I hope I did not mess anything up for you.

Thanks,
Andreas

**Comment by mhscott** [comment]
Thanks, but that reason does not make sense. You can give Dr. Becker's students access to your fork of OpenSees instead of pushing to the main branch.

**Comment by aschellenberg74** [comment]
Great, that makes a lot more sense, will do that from now on.

Sorry again!
Andreas

**Pull request merged**
