### PR TITLE
fix some bugs in InertiaTruss.cpp

### PR DESCRIPTION
**Pull request by Xiaodong-Ji-THU**
fix bugs as listed below:
1. Correct the recorder for axialForce and relativeAcceleration.
2. Set the stiffness to be zero.

### CODE REVIEW

**Comment by mhscott** [comment]
You closed the pull request. Is there additional code you need to add or was this an error? If you reopen the PR, we'll merge it.

**Comment by Xiaodong-Ji-THU** [comment]
Thank you. We have reopened the

**Comment by Xiaodong-Ji-THU** [comment]
Thank you. We have reopened the PR.

**Comment by Xiaodong-Ji-THU** [comment]
> 
> 
> You closed the pull request. Is there additional code you need to add or was this an error? If you reopen the PR, we'll merge it.

Thank you. We have reopened the PR.

**Pull request merged**
