### PR TITLE
FlagShape uniaxial material from Chin-Long Lee

### PR DESCRIPTION
**Pull request by mhscott**

### CODE REVIEW

**Comment by silviamazzoni** [comment]
Thank you for taking on these thankless tasks!

**Comment by mhscott** [comment]
Thanks, @silviamazzoni! Next I'll write the .rst file over in OpenSeesDocumentation

**Comment by fmckenna** [comment]
awaiting documentation with an example

**Comment by mhscott** [comment]
@fmckenna https://github.com/OpenSees/OpenSeesDocumentation/commit/9a092d6b1c40323ab7cf3870dc8327dc23d42cef

**Pull request merged**
