### PR TITLE
An asynchronous parallel double-stage friction-metallic damper

### PR DESCRIPTION
**Pull request by buceaxll**
incorporated an uniaxialMaterial model that simulates the hysteretic responses (axial load-deformation relationship) of an asynchronous parallel friction-metallic dampe (APDFMD) with specific parameters.

### CODE REVIEW

**Review by fmckenna — COMMENTED** [review]
this just add the class .. you have not made changes to the interpreters

**Comment by mhscott** [comment]
The vectors in `sendSelf` and `recvSelf` should be length 20

**Comment by mhscott** [comment]
@buceaxll Same comment about the files added via https://github.com/OpenSees/OpenSees/pull/1388/files (sorry we didn't notic this before)

You have to modify `SRC/interpreter/OpenSeesUniaxialMaterials.cpp` and `SRC/material/uniaxial/TclModelBuilderUniaxialMaterialCommand.cpp` in order for the materials to be usable via Python and Tcl scripts. Look at how other materials are handled in these files.

**Comment by buceaxll** [comment]
Resolved issues (#1388, #1417):
- Fixed vector in sendSelf and recvSelf functions.
- Updated SRC/actor/objectBroker/FEM_ObjectBrokerAllClasses.cpp and SRC/material/uniaxial/CMakeLists.txt.
- Modified SRC/interpreter/OpenSeesUniaxialMaterials.cpp and SRC/material/uniaxial/TclModelBuilderUniaxialMaterialCommand.cpp to enable material usage through Python and Tcl scripts.
Thank you for your support! These modifications ensure the program functions correctly.

**Pull request merged**
