### PR TITLE
Fixes and updates for SectionRepres.

### PR DESCRIPTION
**Pull request by nemaarpit**
Fix deletion of fibers in FiberSectionRepr object . Only temporary fibers created for patches and layers should be deleted.
Utilize the static theSectionRepresObjects created inside SectionRepres.cpp; call OPS_addSectionRepres and OPS_getSectionRepres.
Call OPS_clearAllSectionRepres when wipe command is issued.

### CODE REVIEW

**Comment by mhscott** [comment]
Can you provide a use case or minimal example that shows how this PR is beneficial?

**Comment by nemaarpit** [comment]
The fiber deletion is deleting fibers from the FiberSectionRepr, while leaving patches and layers alone. This is logically inconsistent and breaks the object since numSectionRepresFibers is not set to 0.

The change to use OPS_addSectionRepres and OPS_getSectionRepres is to bring the implementation in line with Sections: see TclModelBuilder::addSection vs TclModelBuilder::addSectionRepres .

A benefit of using OPS_* functions is the access to theSectionRepresObjects Map without needing access to the TclModelBuilder object for the intended final use:
The intended use case is to include the section representation in the json output for post-processing.

- The fiber section json output does not include information about how the section was formed i.e. circular, quad etc.
- The fiber z location is not included in 2D sections.

**Comment by mhscott** [comment]
You PR does not change the OPS_ functions. Is there more code you need to commit/push?

**Comment by nemaarpit** [comment]
This code is standalone, with no effect on functionality.
I will be pushing more code targeting the JSON items in a separate PR. The patch for that PR is attached.
[JSON_FiberSectionRepres.patch](https://github.com/OpenSees/OpenSees/files/15083632/JSON_FiberSectionRepres.patch)

**Comment by nemaarpit** [comment]
The proposed JSON additions have been added to this pull request.

**Comment by mhscott** [comment]
Can you provide a short script here that shows the changes work. I would like to locally pull and test your PR before merging. The changes you have proposed may have bigger implications beyond post-processing.

**Comment by nemaarpit** [comment]
Here are slightly modified copies of MomentCurvature.tcl, and RCFrame4.tcl.
The two scripts are for two different models and can be run separately
[Examples.zip](https://github.com/OpenSees/OpenSees/files/15169160/Examples.zip)

**Comment by mhscott** [comment]
Please post a short script here using Markdown of a simple something, like a zeroLengthSection element with elastic fibers. I don't want to deal with zip files. Sorry.

**Comment by nemaarpit** [comment]
Here is one.
`model basic -ndm 2 -ndf 3

uniaxialMaterial Concrete01  1  -6.0  -0.004   -5.0     -0.014

uniaxialMaterial Concrete01  2  -5.0   -0.002   0.0     -0.006

uniaxialMaterial Steel01  3  60 30000 0.01

set colWidth 15
set colDepth 24 

set cover  1.5
set As    0.60;

set y1 [expr $colDepth/2.0]
set z1 [expr $colWidth/2.0]

section Fiber 1 {
    patch rect 1 10 1 [expr $cover-$y1] [expr $cover-$z1] [expr $y1-$cover] [expr $z1-$cover]
    patch rect 2 10 1  [expr -$y1] [expr $z1-$cover] $y1 $z1
    patch rect 2 10 1  [expr -$y1] [expr -$z1] $y1 [expr $cover-$z1]
    layer straight 3 3 $As [expr $y1-$cover] [expr $z1-$cover] [expr $y1-$cover] [expr $cover-$z1]
    layer straight 3 3 $As [expr $cover-$y1] [expr $z1-$cover] [expr $cover-$y1] [expr $cover-$z1]
}    

set Ky [expr 0.002/(0.7*($colDepth-$cover))*15]
set numIncr 100;	# Number of analysis increments

node 1 0.0 0.0
node 2 0.0 0.0

fix 1 1 1 1
fix 2 0 1 0

element zeroLengthSection  1   1   2  1

pattern Plain 1 "Constant" {
	load 2 -180 0.0 0.0
}

integrator LoadControl 0.0
system SparseGeneral -piv;
test NormUnbalance 1.0e-9 10
numberer Plain
constraints Plain
algorithm Newton
analysis Static

analyze 1
pattern Plain 2 "Linear" {
	load 2 0.0 0.0 1.0
}
set dK [expr $Ky/$numIncr]
integrator DisplacementControl 2 3 $dK 1 $dK $dK

analyze $numIncr
puts "Analysis finished, printing JSON"
print -JSON -file MC_Simple.json
`

**Pull request merged**
