### PR TITLE
Fix typos in `SRC/`

### PR DESCRIPTION
**Pull request by luzpaz**
This fixes typos in user-facing and non-user-facing code.

### CODE REVIEW

**Comment by luzpaz** [comment]
> Go ahead and spell check the entire SRC/ directory and be done with it!

Will update this PR for all of `SRC/` in the next day or 2

**Comment by mhscott** [comment]
> > Go ahead and spell check the entire SRC/ directory and be done with it!
> 
> Will update this PR for all of `SRC/` in the next day or 2

Haha, you're running a script, right? Or are you going file-by-file and line-by-line manually correcting spelling errors?

**Comment by luzpaz** [comment]
I'm using `codespell` + using regex + eyeballing (so I'm not modifying 3rd party dependencies etc...)

**Comment by luzpaz** [comment]
It will probably be less overwhelming If I keep submitting like this. I've added `SRC/material` to this commit instead of the rest of `SRC/`

**Comment by luzpaz** [comment]
@mhscott  I've split the major subdirectories in to separate commits and then misc. subdirs in to the last commit. It gives the committer flexibility in reviewing and cherrypicking if needed

**Comment by luzpaz** [comment]
The CI is reporting unrelated issue  
```
ERROR: Conflict in hdf5/1.12.0:
    'hdf5/1.12.0' requires 'zlib/1.2.11' while 'libmysqlclient/8.0.25' requires 'zlib/1.2.12'.
    To fix this conflict you need to override the package 'zlib' in your root package.
Error: Process completed with exit code 1.
```

**Comment by luzpaz** [comment]
Rebased. Ready for review

**Comment by luzpaz** [comment]
Rebased

**Pull request merged**
